### ISSUE TITLE
this._sessionKey.replace is not a function

### ISSUE THREAD

**Issue by edencorbin** [deepal/node-dukpt#17]
I'm getting this._sessionKey.replace is not a function when trying to use this library, here is my code, what am I missing:

```
const Dukpt = require('dukpt');

const encryptionBDK = '15235124sdfasdfas1233123';
const ksn = '1234567890123456';

const encryptedCardData = 'asdfasfasd'

const dukpt = new Dukpt(encryptionBDK, ksn);

const options = {
    outputEncoding: 'ascii',
    decryptionMode: '3DES',
    trimOutput: true
};

const decryptedCardData = dukpt.dukptDecrypt(encryptedCardData, options);
console.log(decryptedCardData)
```

And a full error dump:

```
TypeError: this._sessionKey.replace is not a function
    at Dukpt.dukptDecrypt (C:\projects\...\node_modules\←[4mdukpt←[24m\dist\lib\dukpt.lib.js:196:34)
    at Object.<anonymous> (C:\projects\...\test.js:19:33)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m
```

**Comment by deepal** [comment]
This issue is fixed and released in v4.0.2
